name: cloned_from_tj1_copy
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - cffi=1.16.0
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-opencl=12.6.37
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.11.0.15
  - libcurand=10.3.7.37
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnvjitlink=12.1.105
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.14
  - pip=24.2
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.9.19
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - sqlite=3.45.3
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.2.0
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==2.1.0
    - accelerate==1.8.1
    - addict==2.4.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.13
    - aiosignal==1.3.2
    - alabaster==0.7.16
    - annotated-types==0.7.0
    - anthropic==0.53.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.9.0
    - asttokens==2.4.1
    - astunparse==1.6.3
    - async-timeout==4.0.3
    - attrs==25.3.0
    - babel==2.16.0
    - beautifulsoup4==4.12.0
    - bitsandbytes==0.46.0
    - blis==1.2.1
    - boto3==1.38.33
    - botocore==1.38.33
    - cachetools==5.4.0
    - captum==0.2.0
    - catalogue==2.0.10
    - certifi==2025.6.15
    - charset-normalizer==3.4.2
    - cilog==1.3.0
    - click==8.1.8
    - cloudpathlib==0.21.1
    - cloudpickle==3.0.0
    - coloredlogs==15.0.1
    - comm==0.2.2
    - confection==0.1.5
    - contourpy==1.1.1
    - coverage==7.6.1
    - cvxopt==1.3.2
    - cycler==0.12.1
    - cymem==2.0.11
    - cython==3.1.1
    - datasets==3.6.0
    - debugpy==1.8.14
    - decorator==5.1.1
    - dgl==2.1.0
    - dgllife==0.3.2
    - dill==0.3.8
    - distro==1.9.0
    - dive-into-graphs==1.1.0
    - docutils==0.17.1
    - duckdb==1.3.2
    - et-xmlfile==1.1.0
    - eval-type-backport==0.2.2
    - exceptiongroup==1.2.2
    - execnet==2.1.1
    - executing==2.0.1
    - faiss-cpu==1.11.0
    - filelock==3.18.0
    - flatbuffers==25.2.10
    - fonttools==4.46.0
    - frozenlist==1.7.0
    - fsspec==2024.6.1
    - future==1.0.0
    - gdown==5.2.0
    - google-auth==2.32.0
    - google-auth-oauthlib==0.4.6
    - greenlet==3.2.3
    - grpcio==1.64.1
    - gym==0.26.2
    - gym-notices==0.0.8
    - h11==0.16.0
    - h5py==3.11.0
    - hf-xet==1.1.2
    - higher==0.2.1
    - hnswlib==0.8.0
    - html2text==2020.1.16
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.33.4
    - humanfriendly==10.0
    - hydra-core==1.3.2
    - hyperopt==0.2.7
    - idna==3.10
    - imageio==2.35.1
    - imagesize==1.4.1
    - importlib-metadata==8.0.0
    - importlib-resources==6.1.1
    - iniconfig==2.0.0
    - ipykernel==6.25.1
    - ipython==8.18.1
    - jedi==0.19.1
    - jinja2==3.1.2
    - jiter==0.10.0
    - jmespath==1.0.1
    - joblib==1.3.2
    - jsonlines==4.0.0
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - jupyter-client==8.6.3
    - jupyter-core==5.8.1
    - kiwisolver==1.4.5
    - langchain==0.3.26
    - langchain-core==0.3.66
    - langchain-text-splitters==0.3.8
    - langcodes==3.5.0
    - langsmith==0.4.1
    - language-data==1.3.0
    - lazy-loader==0.4
    - lightgbm==4.6.0
    - lightning-utilities==0.10.0
    - littleutils==0.2.2
    - llvmlite==0.41.1
    - marisa-trie==1.2.1
    - markdown==3.6
    - markdown-it-py==3.0.0
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mmcv==1.4.8
    - multidict==6.5.0
    - multiprocess==0.70.16
    - munch==2.5.0
    - murmurhash==1.0.13
    - mypy-extensions==1.0.0
    - nest-asyncio==1.6.0
    - networkx==2.8
    - nmslib==2.1.1
    - numba==0.58.1
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.7.0.84
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu11==2.19.3
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.6.20
    - nvidia-nvtx-cu11==11.8.86
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - ogb==1.3.6
    - omegaconf==2.3.0
    - onnxruntime==1.19.2
    - openai==1.67.0
    - opencv-python==4.10.0.84
    - openpyxl==3.1.5
    - orjson==3.10.18
    - outdated==0.2.2
    - packaging==23.2
    - pandas==1.5.3
    - parso==0.8.4
    - peft==0.15.2
    - pexpect==4.9.0
    - pillow==11.2.1
    - platformdirs==4.2.2
    - pluggy==1.5.0
    - pooch==1.8.2
    - preshed==3.0.10
    - prompt-toolkit==3.0.47
    - propcache==0.3.2
    - protobuf==3.20.1
    - psutil==5.9.6
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - py==1.11.0
    - py4j==0.10.9.7
    - pyarrow==20.0.0
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pybind11==2.6.1
    - pydantic==2.11.7
    - pydantic-core==2.33.2
    - pyg-lib==0.4.0+pt22cu118
    - pygcl==0.1.2
    - pygments==2.19.2
    - pyjnius==1.6.1
    - pymetis==2023.1.1
    - pynvml==11.5.0
    - pyparsing==3.1.1
    - pyscf==2.6.2
    - pyserini==0.22.1
    - pytest==7.4.0
    - pytest-cov==3.0.0
    - pytest-forked==1.6.0
    - pytest-xdist==2.5.0
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.0
    - python-graphviz==0.20.3
    - python-leetcode==1.2.1
    - python-louvain==0.16
    - python-slugify==8.0.4
    - pytorch-lightning==2.1.2
    - pytz==2025.2
    - pyzmq==27.0.0
    - rdkit==2024.3.3
    - rdkit-pypi==2022.9.5
    - regex==2024.5.15
    - relbench==1.1.0
    - requests==2.32.4
    - requests-oauthlib==2.0.0
    - requests-toolbelt==1.0.0
    - rich==13.9.4
    - rsa==4.9
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.8
    - s3transfer==0.13.0
    - safetensors==0.4.3
    - scikit-image==0.24.0
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - seaborn==0.13.2
    - sentencepiece==0.2.0
    - setuptools==59.5.0
    - shap==0.46.0
    - shellingham==1.5.4
    - six==1.17.0
    - slicer==0.0.8
    - slugify==0.0.1
    - smart-open==7.1.0
    - sniffio==1.3.1
    - snowballstemmer==2.2.0
    - soupsieve==2.5
    - spacy==3.8.7
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - sphinx==5.3.0
    - sphinx-rtd-theme==1.0.0
    - sphinxcontrib-applehelp==2.0.0
    - sphinxcontrib-devhelp==2.0.0
    - sphinxcontrib-htmlhelp==2.1.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==2.0.0
    - sphinxcontrib-serializinghtml==2.0.0
    - sqlalchemy==2.0.41
    - srsly==2.5.1
    - stack-data==0.6.3
    - tabulate==0.9.0
    - tenacity==9.1.2
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.4.0
    - text-unidecode==1.3
    - texttable==1.7.0
    - thinc==8.3.4
    - threadpoolctl==3.2.0
    - tifffile==2024.8.10
    - together==1.4.6
    - tokenizers==0.21.2
    - tomli==2.0.1
    - torch==2.2.0+cu118
    - torch-cluster==1.6.3+pt22cu118
    - torch-geometric==2.4.0
    - torch-scatter==2.1.2+pt22cu118
    - torch-sparse==0.6.18+pt22cu118
    - torch-spline-conv==1.2.2+pt22cu118
    - torchdata==0.7.1
    - torchmetrics==1.2.1
    - torchvision==0.19.0
    - torchviz==0.0.2
    - tornado==6.5.1
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==4.49.0
    - triton==3.0.0
    - typed-argument-parser==1.7.2
    - typer==0.15.4
    - typing-extensions==4.14.0
    - typing-inspect==0.9.0
    - typing-inspection==0.4.1
    - tzdata==2025.2
    - umap==0.1.1
    - urllib3==2.5.0
    - wasabi==1.1.3
    - wcwidth==0.2.13
    - weasel==0.4.1
    - werkzeug==3.0.3
    - wilds==2.0.0
    - wrapt==1.17.2
    - xxhash==3.5.0
    - yacs==0.1.8
    - yapf==0.40.2
    - yarl==1.20.1
    - zipp==3.17.0
    - zstandard==0.23.0
